#!/bin/bash

# Gather system information
USER=$(whoami)
DATE=$(date)
HOSTNAME=$(hostname)
OS_VERSION=$(grep -E '^NAME|^VERSION' /etc/os-release | awk -F= '{print $2}' | tr -d '"')
UPTIME=$(uptime -p)

# Hardware Details
CPU_MODEL=$(lscpu | grep "Model name" | cut -d ':' -f2 | sed 's/^ *//')
CPU_COUNT=$(nproc)
CPU_FREQ=$(lscpu | grep "CPU MHz" | awk '{print $3 " MHz"}')
MEMORY=$(free -h | grep Mem | awk '{print $2}')
RAM_VENDOR=$(sudo dmidecode -t memory | grep -m1 "Manufacturer" | awk -F ': ' '{print $2}')
DISK_LIST=$(lsblk -d -o NAME,MODEL,SIZE | grep -E "^sd|^nvme")
GRAPHICS_CARD=$(lspci | grep -i 'vga\|display' | cut -d ':' -f3 | sed 's/^ *//')

# Network Configuration
INTERFACE_NAMES=$(ip -o link show | awk -F': ' '{print $2}')
FQDN=$(hostname -f)
IP_ADDRESS=$(ip -4 addr show | grep "inet " | awk '{print $2}' | cut -d'/' -f1 | head -n 1)
ROUTER_IP=$(ip route | grep default | awk '{print $3}')
DNS_SERVERS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd ", ")

# System Information
LOGGED_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ", ")
USED_DISK_SPACE=$(df -h | grep '^/' | awk '{print $6 " " $4}' | column -t)
ACTIVE_PROCESSES=$(ps aux --no-headers | wc -l)
SYSTEM_LOAD=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')
OPEN_PORTS=$(ss -tuln | awk '{print $5}' | cut -d':' -f2 | grep -Eo '[0-9]+' | sort -nu | paste -sd ", ")
FIREWALL_STATUS=$(sudo ufw status | grep "Status" | awk '{print $2}')

# Generating the System Report
echo ""
echo "System Information Report - Generated by $USER on $DATE"
echo ""
echo "System Overview"
echo "----------------"
echo "Hostname: $HOSTNAME"
echo "OS Version: $OS_VERSION"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Details"
echo "-----------------"
echo "CPU: $CPU_MODEL ($CPU_COUNT cores, $CPU_FREQ)"
echo "Memory: $MEMORY (Manufacturer: $RAM_VENDOR)"
echo "Disks: $DISK_LIST"
echo "Graphics: $GRAPHICS_CARD"
echo ""
echo "Network Configuration"
echo "----------------------"
echo "Network Interfaces: $INTERFACE_NAMES"
echo "Fully Qualified Domain Name: $FQDN"
echo "IP Address: $IP_ADDRESS"
echo "Gateway IP: $ROUTER_IP"
echo "DNS Servers: $DNS_SERVERS"
echo ""
echo "System Status"
echo "-------------"
echo "Logged-in Users: $LOGGED_USERS"
echo "Disk Usage: $USED_DISK_SPACE"
echo "Active Processes: $ACTIVE_PROCESSES"
echo "System Load Averages: $SYSTEM_LOAD"
echo "Open Network Ports: $OPEN_PORTS"
echo "Firewall Status: $FIREWALL_STATUS"
echo ""
